"""avoidance.py — exp_001 rebuilt from its frozen spec, as committed code.

WHY THIS EXISTS. PLAN_3 §6R: "Finding 001 is not reproducible. The
registration was correctly ordered and the spec genuinely frozen, but the
analysis code was never committed." Its recorded result (+0.237%/yr FIT,
−0.022%/yr TEST, REJECTED) could be regenerated by nobody. This module is the
spec, executed. It is a RECONSTRUCTION: where the spec is silent, the choice
is named here and in the report, and the original figures are not expected to
come back exactly.

THE SPEC (experiment_registry, exp_001_bulk_deal_avoidance_filter):
  books      equal-weighted point-in-time top 500 (seed pit_universe, monthly),
             unfiltered vs the same book EXCLUDING names with a directional
             bulk-deal BUY in the trailing 10 sessions; paired difference
  events     directional bulk BUY: same-day round trips and PROP_HFT excluded
  timing     disclosure observable after the close of day d; entry at the
             next session's OPEN; eligible again 10 sessions later
  costs      29.33 bps round trip on the INCREMENTAL turnover the filter causes
  inference  paired-difference moving-block bootstrap, block 10 sessions,
             10,000 draws, seed 0
  pass bar   annualised net difference > +0.25%/yr AND 95% CI excluding zero,
             in BOTH holdouts
  period     2006-01-02 .. 2026-08-14

CHOICES THE SPEC DID NOT MAKE (named, not hidden):
  * holding returns are OPEN-to-OPEN, so "entry at the next open" is exact: a
    name bought on day d is out of the filtered book for the holding days
    d+1 .. d+10 (open of d+1 to open of d+11)
  * bulk deals only, not block — the spec says "bulk-deal BUY"
  * cost per exclusion episode = 2 x (1/N) x 29.33 bps: the name is sold and
    its weight spread over the rest on exit, and the reverse on re-entry.
    Tiered slippage is named in the spec but not specified; not modelled
  * the STOCK-SPLIT HOLDOUT's rule was never recorded. Here: security_id
    parity (even = FIT, odd = TEST), and the result over SPLITS random
    splits, so the reader sees how much the split itself moves the answer
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import duckdb  # noqa: E402
import numpy as np  # noqa: E402

from src.common.paths import CONFIGS, DOCS, research_db  # noqa: E402

WINDOW = 10
ROUND_TRIP = 0.002933
BAR = 0.0025
DRAWS = 10_000
BLOCK = 10
SEED = 0
SPLITS = 200
START, END = date(2006, 1, 2), date(2026, 8, 14)
REPORT = DOCS / "reports" / "FINDING_001_RECONSTRUCTED.md"


def bulk_buys(dates: list, ids: np.ndarray, env: str | None = None) -> np.ndarray:
    """T x N bool: a directional bulk BUY by an eligible participant on day t."""
    di = {d: i for i, d in enumerate(dates)}
    ii = {int(s): j for j, s in enumerate(ids)}
    out = np.zeros((len(dates), len(ids)), dtype=bool)
    con = duckdb.connect(str(research_db(env)), read_only=True)
    try:
        for d, s in con.execute("""
                SELECT DISTINCT trade_date, security_id FROM institutional_deals_clean
                WHERE security_id IS NOT NULL AND deal_type = 'BULK' AND side = 'BUY'
                  AND NOT same_day_round_trip_flag
                  AND COALESCE(ineligibility_reason, '') NOT IN
                      ('same-day round trip', 'PROP_HFT participant', 'unparseable side',
                       'unparseable quantity or price')""").fetchall():
            if d in di and int(s) in ii:
                out[di[d], ii[int(s)]] = True
    finally:
        con.close()
    return out


def excluded(events: np.ndarray, window: int = WINDOW) -> np.ndarray:
    """T x N bool: out of the filtered book on holding day t. An event on day
    d excludes holding days d+1 .. d+window (open d+1 to open d+window+1)."""
    T = events.shape[0]
    ex = np.zeros_like(events)
    for lag in range(1, window + 1):
        ex[lag:] |= events[:T - lag]
    return ex


def open_to_open(open_: np.ndarray) -> np.ndarray:
    """r[t] = open[t+1] / open[t] - 1; NaN where either is missing, last row NaN."""
    r = np.full(open_.shape, np.nan, dtype=np.float64)
    with np.errstate(invalid="ignore", divide="ignore"):
        r[:-1] = open_[1:] / open_[:-1] - 1
    r[~np.isfinite(r)] = np.nan
    return r


def paired_net(ret: np.ndarray, universe: np.ndarray, ex: np.ndarray, names: np.ndarray,
               round_trip: float = ROUND_TRIP) -> np.ndarray:
    """Daily filtered-minus-unfiltered return, net of the filter's incremental
    cost, over `names` (N bool). NaN on days with no eligible names."""
    held = universe & np.isfinite(ret) & names[None, :]
    filt = held & ~ex
    r0 = np.where(held, ret, 0.0)
    n_all, n_f = held.sum(1), filt.sum(1)
    with np.errstate(invalid="ignore", divide="ignore"):
        unf = r0.sum(1) / n_all
        fil = np.where(filt, ret, 0.0).sum(1) / n_f
        # Episodes starting and ending today among held names: each costs
        # 2 x (1/N) of a round trip (exit and re-entry each trade 2/N one-way).
        prev = np.vstack([np.zeros((1, ex.shape[1]), bool), ex[:-1]])
        changes = (held & (ex != prev)).sum(1)
        cost = changes * (1.0 / n_f) * round_trip
    d = fil - unf - cost
    d[(n_all == 0) | (n_f == 0)] = np.nan
    return d


def block_bootstrap_ci(x: np.ndarray, draws: int = DRAWS, block: int = BLOCK,
                       seed: int = SEED) -> tuple[float, float, float]:
    """(mean, 2.5%, 97.5%) of the mean, moving blocks of `block` days, annualised x252."""
    x = x[np.isfinite(x)]
    n = len(x)
    rng = np.random.default_rng(seed)
    k = -(-n // block)
    starts = rng.integers(0, n - block + 1, size=(draws, k))
    idx = (starts[:, :, None] + np.arange(block)[None, None, :]).reshape(draws, -1)[:, :n]
    means = x[idx].mean(1) * 252
    lo, hi = np.percentile(means, [2.5, 97.5])
    return float(x.mean() * 252), float(lo), float(hi)


@dataclass
class Holdout:
    name: str
    days: int
    annual: float
    ci_low: float
    ci_high: float
    t: float

    @property
    def passes(self) -> bool:
        return self.annual > BAR and self.ci_low > 0


def _holdout(name: str, d: np.ndarray, draws: int) -> Holdout:
    x = d[np.isfinite(d)]
    a, lo, hi = block_bootstrap_ci(x, draws)
    se = (hi - lo) / (2 * 1.96) if hi > lo else float("nan")
    return Holdout(name, len(x), a, lo, hi, a / se if se else float("nan"))


def quarantine_mask(dates: list, ids: np.ndarray, symbols: dict[int, str] | None) -> np.ndarray:
    """T x N bool: holding days whose open-to-open return crosses a day in
    configs/price_suspect_days.csv (decision 0088)."""
    import csv
    m = np.zeros((len(dates), len(ids)), dtype=bool)
    if not symbols:
        return m
    di = {d.isoformat(): i for i, d in enumerate(dates)}
    by_sym: dict[str, list[int]] = {}
    for j, s in enumerate(ids):
        sym = symbols.get(int(s))
        if sym:
            by_sym.setdefault(sym, []).append(j)
    with (CONFIGS / "price_suspect_days.csv").open() as fh:
        for r in csv.DictReader(fh):
            t = di.get(r["date"])
            for j in by_sym.get(r["symbol"], []):
                if t is not None:
                    m[max(t - 1, 0):t + 1, j] = True   # open t-1 -> open t, and open t -> open t+1
    return m


def run(env: str | None = None, draws: int = DRAWS, quarantine: bool = False) -> dict:
    from src.scan import panel as P
    p = P.load(env, start=START, end=END)
    ret = open_to_open(p.open)
    if quarantine:
        con = duckdb.connect(str(research_db(env)), read_only=True)
        syms = dict(con.execute("SELECT security_id, canonical_symbol FROM security_master").fetchall())
        con.close()
        ret[quarantine_mask(p.dates, p.ids, syms)] = np.nan
    ev = bulk_buys(p.dates, p.ids, env) & p.universe
    ex = excluded(ev)
    even = (np.asarray(p.ids) % 2 == 0)
    fit = _holdout("FIT (even security_id)", paired_net(ret, p.universe, ex, even), draws)
    test = _holdout("TEST (odd security_id)", paired_net(ret, p.universe, ex, ~even), draws)
    rng = np.random.default_rng(SEED)
    split_ann, split_pass = [], 0
    for _ in range(SPLITS):
        half = rng.random(len(p.ids)) < 0.5
        a = paired_net(ret, p.universe, ex, half)
        b = paired_net(ret, p.universe, ex, ~half)
        ha, hb = _holdout("a", a, 500), _holdout("b", b, 500)
        split_ann += [ha.annual, hb.annual]
        split_pass += ha.passes and hb.passes
    every = np.ones(len(p.ids), bool)
    full = _holdout("ALL names", paired_net(ret, p.universe, ex, every), draws)
    # Gross of the filter's cost, so the reader sees the effect and the cost apart.
    gross = _holdout("ALL names, GROSS of cost", paired_net(ret, p.universe, ex, every, round_trip=0.0), draws)
    return {"fit": fit, "test": test, "full": full, "gross": gross, "events": int(ev.sum()),
            "split_annual_pct": [float(np.percentile(split_ann, q)) for q in (5, 50, 95)],
            "split_both_pass": split_pass, "days": len(p.dates), "names": len(p.ids)}


def render(base: dict, quar: dict) -> str:
    def row(h: Holdout) -> str:
        return (f"| {h.name} | {h.days:,} | {h.annual:+.3%} | [{h.ci_low:+.3%}, {h.ci_high:+.3%}] | "
                f"{h.t:+.2f} | {'PASS' if h.passes else 'FAIL'} |")
    lines = [
        "# FINDING_001_RECONSTRUCTED.md — exp_001 rebuilt from its frozen spec",
        "",
        "**Generated by `python -m src.research.avoidance`. A RECONSTRUCTION: the original analysis code "
        "was never committed (PLAN_3 §6R). Choices the spec did not make are named in the module "
        "docstring. Nothing here is written to the registry; the recorded verdict (REJECTED) stands.**",
        "",
        "Recorded (2026-08-17, uncommitted code, uncorrected prices): FIT **+0.237%/yr** (t +3.11, CI "
        "[+0.089%, +0.386%]); TEST **−0.022%/yr** (t −0.25). Bar: > +0.25%/yr and CI above zero in BOTH.",
        "",
    ]
    for title, r in (("Corrected spine (decision 0088)", base),
                     ("Corrected spine, quarantined days excluded", quar)):
        lines += [f"## {title}", "",
                  f"{r['events']:,} directional bulk-buy events in the universe; {r['days']:,} sessions.", "",
                  "| holdout | days | annualised net difference | 95% CI (block bootstrap) | t | bar |",
                  "|---|---:|---:|---|---:|---|",
                  row(r["fit"]), row(r["test"]), row(r["full"]), row(r["gross"]), "",
                  f"Over {SPLITS} random name splits: the half-book difference runs "
                  f"{r['split_annual_pct'][0]:+.3%} / {r['split_annual_pct'][1]:+.3%} / "
                  f"{r['split_annual_pct'][2]:+.3%} (5th / 50th / 95th percentile); both halves clear "
                  f"the bar in {r['split_both_pass']} of {SPLITS}.", ""]
    return "\n".join(lines) + "\n"


def main() -> int:
    base, quar = run(), run(quarantine=True)
    text = render(base, quar)
    REPORT.write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
