"""measure.py — regenerate the power grid decision 0034 rests on. Committed code.

WHY THIS FILE EXISTS, AND IT IS NOT A GOOD REASON.

`PLAN_3` §6R records the predecessor finding's defect:

    "Finding 001 is not reproducible. The registration was correctly ordered and
     the spec genuinely frozen, but the analysis code was never committed, and
     the holdout is recorded as prose ... Nobody can regenerate +0.237%/yr or
     -0.022%/yr, including me."

On 2026-08-23 I measured the twelve-month horizon, found it the only one within
reach of its bound, and the owner made it the primary horizon
([0034](../../docs/decisions/0034-twelve-month-becomes-the-primary-horizon.md)).
That measurement was run in throwaway shell heredocs. **The analysis code was
never committed.** The number in the decision record, in the report, and in the
README could not be regenerated by anyone, including me.

That is exp_001's defect, committed inside the project whose subject is that
defect, four days after cataloguing it. This module is the correction: the grid
is code, it runs from committed inputs, and a test pins the headline value so it
cannot drift silently.

WHAT IT DELIBERATELY DOES NOT DO. It does not estimate an effect. Only
dispersion — cohort SD, serial inflation, MDE — which decision 0035 permits on
the full universe precisely because it cannot distinguish a true effect from a
false one. The moment this file computes a mean return it must move behind the
ConfirmationGuard and charge a trial family.
"""

from __future__ import annotations

from dataclasses import dataclass

import duckdb

from src.common.paths import warehouse_dir
from src.mart import eligibility
from src.research import power

#: Horizons in trading sessions, with the months they represent. The bound
#: scales linearly with horizon (decision 0028) and 21 sessions is the
#: convention for one month, from research.yml `sessions_per_month`.
HORIZONS: tuple[tuple[str, int, float], ...] = (
    ("21s (1m)", 21, 1.0),
    ("63s (3m)", 63, 3.0),
    ("252s (12m)", 252, 12.0),
)

#: research.yml power.plausible_effect_bound_monthly
BOUND_PER_MONTH = 0.005

#: configs/participants.yml eligibility. A deal must be economically real before
#: it is an event: at least Rs 1 crore AND at least 0.5% of 20-day ADV.
MIN_VALUE_INR = 1e7
MIN_VALUE_TO_ADV = 0.005


@dataclass(frozen=True, slots=True)
class Row:
    horizon: str
    sessions: int
    months: float
    n_events: int
    n_cohorts: int
    cohort_sd: float
    inflation: float
    mde: float

    @property
    def bound(self) -> float:
        return BOUND_PER_MONTH * self.months

    @property
    def powered(self) -> bool:
        return self.mde <= self.bound

    def render(self) -> str:
        verdict = "POWERED" if self.powered else f"{self.mde / self.bound:.2f}x short"
        return (
            f"  {self.horizon:>11} {self.n_events:>7,} {self.n_cohorts:>4} "
            f"{self.cohort_sd:>9.4%} {self.inflation:>6.2f} {self.mde:>9.4%} "
            f"{self.bound:>8.2%} {verdict:>14}"
        )


def _returns_sql(spine: str, sessions: int) -> str:
    """Forward return over `sessions`, entered at the OPEN of the session AFTER
    the trade date — never the same session's close, because the disclosure is
    published after that close (`configs/research.yml` timing.no_same_day_close).
    """
    return f"""
    WITH px AS (
        SELECT symbol, date, open, close, volume,
               ROW_NUMBER() OVER (PARTITION BY symbol ORDER BY date) AS i
        FROM read_parquet('{spine}') WHERE close > 0 AND open > 0
    ),
    f AS (
        SELECT a.symbol, a.date,
               LEAD(a.open, 1) OVER w AS entry,
               LEAD(a.close, {sessions}) OVER w AS exit_px,
               median(a.close * a.volume) OVER (
                   PARTITION BY a.symbol ORDER BY a.i ROWS BETWEEN 19 PRECEDING AND CURRENT ROW
               ) AS adv20
        FROM px a WINDOW w AS (PARTITION BY a.symbol ORDER BY a.i)
    )
    SELECT symbol, date, adv20, exit_px / entry - 1 AS ret FROM f WHERE entry > 0
    """


def grid(env: str | None = None) -> list[Row]:
    """The power grid, from the adjusted spine and the eligibility filter.

    THE ADJUSTED SPINE, NOT THE RAW ONE. `universe.yml` sets
    `research_prices: adjusted`; on raw prices a 1:2 split reads as -50%.
    """
    spine = str(warehouse_dir(env) / "price_spine_adj" / "**" / "*.parquet")
    con = duckdb.connect()
    con.execute("SET memory_limit='8GB'; SET preserve_insertion_order=false; SET threads=4;")
    eligibility.classify(con)

    out: list[Row] = []
    for label, sessions, months in HORIZONS:
        con.execute(f"CREATE OR REPLACE VIEW rets AS {_returns_sql(spine, sessions)}")
        # Market-relative: the equal-weighted cross-sectional mean of the same
        # session. Decision 0021 — a pooled average of market-relative returns is
        # identically zero, so the demean is the comparison, not the estimator.
        con.execute("CREATE OR REPLACE VIEW mkt AS SELECT date, avg(ret) m FROM rets GROUP BY 1")
        df = con.execute(
            "SELECT e.date AS tdate, e.value_inr, r.adv20, r.ret - m.m AS ab"
            " FROM eligible_events e"
            " JOIN rets r ON r.symbol = e.symbol AND r.date = e.date"
            " JOIN mkt m ON m.date = e.date"
        ).df().dropna(subset=["ab"])
        df = df[(df.value_inr >= MIN_VALUE_INR) & (df.adv20 > 0)
                & (df.value_inr / df.adv20 >= MIN_VALUE_TO_ADV)]

        cohorts = power.cohort_collapse(df["tdate"], df["ab"], freq="M")
        # THE LAG MUST COVER THE LABEL OVERLAP (decision 0033). A 12-month label
        # on monthly cohorts overlaps 11/12; the Newey-West rule alone picks ~5
        # and understates the correction, which is what briefly made this look
        # POWERED when it was not.
        label_periods = max(1, round(months))
        infl, _ = power.serial_inflation(cohorts, label_periods=label_periods)
        out.append(Row(
            horizon=label, sessions=sessions, months=months,
            n_events=len(df), n_cohorts=len(cohorts),
            cohort_sd=power.cohort_sd(cohorts), inflation=infl,
            mde=power.mde_serial_corrected(cohorts, label_periods=label_periods),
        ))
    return out


def main() -> int:
    print("POWER GRID — eligible, size-filtered, market-relative, adjusted spine")
    print("  bound scales with horizon (decision 0028); lag covers the label overlap (0033)")
    print(f"\n  {'horizon':>11} {'n':>7} {'coh':>4} {'sd':>9} {'infl':>6} "
          f"{'MDE':>9} {'bound':>8} {'verdict':>14}")
    rows = grid()
    for r in rows:
        print(r.render())
    powered = [r for r in rows if r.powered]
    print(f"\n  {len(powered)} of {len(rows)} horizons reach their bound"
          + (f": {', '.join(r.horizon for r in powered)}" if powered else ""))
    if powered:
        print("  Reported as MARGINAL. A study registered here sits near its own")
        print("  detection floor, which is the condition power.py exists to flag.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
