"""measure.py — regenerate the power grid decision 0034 rests on. Committed code.

WHY THIS FILE EXISTS, AND IT IS NOT A GOOD REASON.

`PLAN_3` §6R records the predecessor finding's defect:

    "Finding 001 is not reproducible. The registration was correctly ordered and
     the spec genuinely frozen, but the analysis code was never committed, and
     the holdout is recorded as prose ... Nobody can regenerate +0.237%/yr or
     -0.022%/yr, including me."

On 2026-08-23 I measured the twelve-month horizon, found it the only one within
reach of its bound, and the owner made it the primary horizon
([0034](../../docs/decisions/0034-twelve-month-becomes-the-primary-horizon.md)).
That measurement was run in throwaway shell heredocs. **The analysis code was
never committed.** The number in the decision record, in the report, and in the
README could not be regenerated by anyone, including me.

That is exp_001's defect, committed inside the project whose subject is that
defect, four days after cataloguing it. This module is the correction: the grid
is code, it runs from committed inputs, and a test pins the headline value so it
cannot drift silently.

WHAT IT DELIBERATELY DOES NOT DO. It does not estimate an effect. Only
dispersion — cohort SD, serial inflation, MDE — which decision 0035 permits on
the full universe precisely because it cannot distinguish a true effect from a
false one. The moment this file computes a mean return it must move behind the
ConfirmationGuard and charge a trial family.
"""

from __future__ import annotations

from dataclasses import dataclass

import duckdb

from src.common.paths import research_db, warehouse_dir
from src.research import power

#: Horizons in trading sessions, with the months they represent. The bound
#: scales linearly with horizon (decision 0028) and 21 sessions is the
#: convention for one month, from research.yml `sessions_per_month`.
HORIZONS: tuple[tuple[str, int, float], ...] = (
    ("21s (1m)", 21, 1.0),
    ("63s (3m)", 63, 3.0),
    ("252s (12m)", 252, 12.0),
)

def _bound_per_month() -> float:
    """The plausible effect bound, READ FROM research.yml rather than restated.

    This was `BOUND_PER_MONTH = 0.005` — a literal that happened to equal
    `power.plausible_effect_bound_monthly` and was not connected to it. Editing
    the config would have changed nothing and said nothing, which matters more
    than usual here: 0044 found the observed sell effect is 4x this bound, so
    whether 0011's 0.5%/month is right is now the project's live question. A
    config the verdicts ignore is a config that cannot answer it.

    Found by an external audit, 2026-09-02.
    """
    import yaml

    from src.common.paths import CONFIGS

    spec = yaml.safe_load((CONFIGS / "research.yml").read_text())
    return float(spec["power"]["plausible_effect_bound_monthly"])


#: Resolved once at import. research.yml is frozen for a run by definition; a
#: bound that could change mid-measurement would make two rows incomparable.
BOUND_PER_MONTH = _bound_per_month()

#: configs/participants.yml eligibility. A deal must be economically real before
#: it is an event: at least Rs 1 crore AND at least 0.5% of 20-day ADV.
MIN_VALUE_INR = 1e7
MIN_VALUE_TO_ADV = 0.005


@dataclass(frozen=True, slots=True)
class Row:
    horizon: str
    sessions: int
    months: float
    n_events: int
    n_cohorts: int
    cohort_sd: float
    inflation: float
    mde: float

    @property
    def bound(self) -> float:
        return BOUND_PER_MONTH * self.months

    @property
    def powered(self) -> bool:
        return self.mde <= self.bound

    def render(self) -> str:
        verdict = "POWERED" if self.powered else f"{self.mde / self.bound:.2f}x short"
        return (
            f"  {self.horizon:>11} {self.n_events:>7,} {self.n_cohorts:>4} "
            f"{self.cohort_sd:>9.4%} {self.inflation:>6.2f} {self.mde:>9.4%} "
            f"{self.bound:>8.2%} {verdict:>14}"
        )


#: Trading sessions in a calendar year, used only to convert a session horizon
#: into the calendar span it OUGHT to occupy.
SESSIONS_PER_YEAR = 252.0


def max_span_days(sessions: int) -> float:
    """The calendar span a horizon of `sessions` sessions may legitimately take.

    THE SINGLE DEFINITION. `outcomes.py` imports this rather than restating it —
    two thresholds for the same rule are two rules.

    The allowance is 1.5x the expected span plus ten days: generous enough that
    a run of holidays never trips it, tight enough to catch the 707-day
    "twelve-month" windows this project was counting as ordinary.
    """
    return sessions * 365.0 / SESSIONS_PER_YEAR * 1.5 + 10.0



def identified_px_ctes(spine: str, cutoff: str | None = None) -> str:
    """The `px -> ident -> sec` chain, as CTE text for a WITH clause.

    ONE DEFINITION OF "WHICH SECURITY IS THIS PRICE ROW". Decision 0061 moved
    `_returns_sql` to PARTITION BY security_id and left delisting.py with its
    own symbol-partitioned window, so from 2026-09-15 the two modules disagreed
    about how many EXPLORE events exist (1,115 vs 1,080). Extracted 2026-09-16
    so every window in the project resolves identity by the same rule the mart
    used to stamp security_id on the deal — and so the next module cannot start
    a fourth copy.
    """
    cut = f" AND date <= '{cutoff}'" if cutoff else ""
    return f"""px AS (
        SELECT UPPER(TRIM(symbol)) AS symbol, date, open, close, volume
        FROM read_parquet('{spine}') WHERE close > 0 AND open > 0{cut}
    ),
    -- IDENTITY, BY THE IDENTITY LAYER'S OWN RULE (src/identity/master.py
    -- RESOLVE_SQL): a symbol_history window that covers the date wins; else the
    -- nearest window; ties to the lowest security_id. The same ordering the
    -- mart used to stamp security_id on every deal, so deal and price row
    -- agree on the trade date by construction. A spine symbol with no
    -- symbol_history row has no identity and produces no return: its deals
    -- are UNRESOLVED and excluded by every caller, not matched by string.
    ident AS (
        SELECT p.symbol, p.date, p.open, p.close, p.volume, h.security_id,
               CASE WHEN CAST(p.date AS DATE) >= h.valid_from
                     AND (h.valid_to IS NULL OR CAST(p.date AS DATE) <= h.valid_to)
                    THEN 0
                    WHEN CAST(p.date AS DATE) < h.valid_from
                    THEN date_diff('day', CAST(p.date AS DATE), h.valid_from)
                    ELSE date_diff('day', h.valid_to, CAST(p.date AS DATE)) END AS gap_days
        FROM px p JOIN symbol_history h ON h.symbol = p.symbol
        QUALIFY ROW_NUMBER() OVER (PARTITION BY p.symbol, p.date
                                   ORDER BY gap_days, h.security_id) = 1
    ),
    -- One row per security-session. On a rename day both tickers can trade;
    -- keep the one whose window covers the date, then the more liquid one.
    sec AS (
        SELECT * FROM ident
        QUALIFY ROW_NUMBER() OVER (PARTITION BY security_id, date
                                   ORDER BY gap_days, volume DESC, symbol) = 1
    )"""


def _returns_sql(spine: str, sessions: int, cutoff: str | None = None) -> str:
    """Forward return over `sessions`, entered at the OPEN of the session AFTER
    the trade date — never the same session's close, because the disclosure is
    published after that close (`configs/research.yml` timing.no_same_day_close).

    `sessions` MEANS SESSIONS, WHICH IT DID NOT UNTIL 2026-09-05.

    `LEAD(close, N)` counts ROWS of this name's own price history, not sessions
    of the calendar. A name that stops trading and relists supplies its Nth row
    years later, and the result was returned here as an N-session forward
    return. Six modules share this function — measure, consensus, selling,
    insider_power, confounds, delisting — so every power verdict and every
    effect estimate the project has published came through it.

    Measured on the EXPLORE sell population: 37 of 1,145 twelve-month events
    spanned over 500 calendar days, the worst being ATLASCYCLE at 3,506 days
    (9.6 years) at -117.8% abnormal. Those 37 averaged -51.4% against -29.6%
    for the rest.

    A window wider than `max_span_days` did not hold a position for `sessions`
    sessions; it held one across a trading suspension. `ret` is NULL there, so
    such an event is excluded from every mean rather than contributing a
    multi-year return under a one-year label. It is NULL rather than dropped
    because callers count rows: 0052 already established that COUNT(*) and
    avg() disagreeing is how these events hide.

    THE PARTITION IS THE SECURITY, NOT THE TICKER, SINCE 2026-09-15.

    Until then every window ran `PARTITION BY symbol` and every study joined
    `r.symbol = UPPER(TRIM(raw.symbol_raw))`. A ticker is not an identity:
    331 spine symbols were held by more than one security over time and 275
    securities traded under more than one symbol. On a recycled ticker the
    window ran one company's last rows into the next company's first rows; on
    a rename it broke at the old ticker and the event vanished. The identity
    layer had already resolved every deal to a `security_id` and the mart had
    already stored it; the studies threw that away and re-derived identity
    from the string. Every row here now carries `security_id`; `symbol` is
    retained only for the sibling modules that have not yet moved their event
    side off the string (confounds, insider_power, delisting).

    The market benchmark callers build from this view is therefore the mean
    over IDENTIFIED securities — 94.68% of spine rows on 2026-09-15 — not over
    every string in the spine. The 1,008 unmapped symbols are the ones the
    universe already excludes as unresolved.
    """
    return f"""
    WITH {identified_px_ctes(spine, cutoff)},
    f AS (
        SELECT a.security_id, a.symbol, a.date,
               LEAD(a.open, 1) OVER w AS entry,
               LEAD(a.close, {sessions}) OVER w AS exit_px,
               LEAD(a.date, {sessions}) OVER w AS exit_date,
               median(a.close * a.volume) OVER (
                   PARTITION BY a.security_id ORDER BY a.date ROWS BETWEEN 19 PRECEDING AND CURRENT ROW
               ) AS adv20
        FROM sec a WINDOW w AS (PARTITION BY a.security_id ORDER BY a.date)
    )
    SELECT security_id, symbol, date, adv20,
           CASE WHEN date_diff('day', CAST(date AS DATE), CAST(exit_date AS DATE))
                     <= {max_span_days(sessions)}
                THEN exit_px / entry - 1 END AS ret
    FROM f WHERE entry > 0
    """


#: The event horizon the committed figures are quoted at.
#:
#: WHY A FIXED CUTOFF EXISTS AT ALL. Until 2026-09-01 `grid()` measured every
#: event on disk, so its answer moved whenever the collector ran — 4,766 events
#: at 20:00 and 4,790 at 20:22. A decision record quoting "13.2701%" was then
#: unreproducible by the following morning, which is precisely the defect
#: PLAN_3 §6R records about exp_001: *"the analysis code was never committed"*.
#: Committing the code and leaving the DATA unbounded reproduces the same
#: failure one layer down.
#:
#: Raising this is a deliberate act that changes what the quoted figures mean,
#: and it belongs in a decision record alongside the re-measured values.
REPRODUCIBILITY_HORIZON = "2026-08-31"


#: The deal-to-price join. BY SECURITY, NOT BY STRING. `institutional_deals_raw`
#: is not read at all: the identity layer resolved every deal to a security_id
#: at mart build, and `rets` carries the same security_id on every price row.
#: A deal whose identity could not be resolved is excluded here with the
#: reason `unresolved_identity`, counted by UNRESOLVED_SQL, never matched by
#: guessing which company its ticker meant that day.
EVENT_JOIN_SQL = (
    "SELECT cl.trade_date AS tdate, r.ret - m.m AS ab"
    " FROM institutional_deals_clean cl"
    " JOIN rets r ON r.security_id = cl.security_id"
    "            AND r.date = cl.trade_date"
    " JOIN mkt m ON m.date = cl.trade_date"
    " WHERE cl.eligible_for_research"
    "   AND cl.security_id IS NOT NULL"
)

#: Rows the study would otherwise have counted, excluded for unresolved_identity.
#: Structurally 0 today — the mart's unresolved/uncovered exclusions run before
#: eligibility — and reported so that it stays a decision rather than a coincidence.
UNRESOLVED_SQL = (
    "SELECT COUNT(*) FROM institutional_deals_clean"
    " WHERE eligible_for_research AND security_id IS NULL"
)


def unresolved(env: str | None = None) -> int:
    """Eligible rows excluded from every return here for unresolved_identity."""
    con = duckdb.connect(str(research_db(env)), read_only=True)
    try:
        return con.execute(UNRESOLVED_SQL).fetchone()[0]
    finally:
        con.close()


def grid(env: str | None = None, cutoff: str | None = REPRODUCIBILITY_HORIZON) -> list[Row]:
    """The power grid, from the adjusted spine and the eligibility filter.

    THE ADJUSTED SPINE, NOT THE RAW ONE. `universe.yml` sets
    `research_prices: adjusted`; on raw prices a 1:2 split reads as -50%.
    """
    spine = str(warehouse_dir(env) / "price_spine_adj" / "**" / "*.parquet")
    # READ THE MART, NOT THE SEED PARQUET. Until 2026-08-24 this measurement ran
    # off bulk_deals.parquet directly, bypassing the archive, the identity layer
    # and the provenance DAG — so the number decision 0034 rests on had no
    # lineage. It now reads institutional_deals_clean, where every row has been
    # resolved point-in-time, dated against the observed calendar, and given an
    # explicit eligibility reason.
    # READ-ONLY, AND THE VIEWS ARE TEMP. Two defects, one fix.
    #
    # DuckDB takes an exclusive lock on write, so status.py and every study
    # failed outright with "Conflicting lock is held" once collect_daily.sh
    # started running land -> master -> clean three times a session. A reader
    # that cannot read during collection fails exactly when someone looks.
    #
    # Read-only then forbids CREATE VIEW — which is the second defect surfacing:
    # 0047 found eight views left behind in the PRODUCTION database by
    # measurement code, one of which later took the whole status page down. TEMP
    # views are session-local, so they work read-only and vanish on close. The
    # measurement layer should never have been writing to the store it reads.
    con = duckdb.connect(str(research_db(env)), read_only=True)
    con.execute("SET memory_limit='8GB'; SET preserve_insertion_order=false; SET threads=4;")

    out: list[Row] = []
    for label, sessions, months in HORIZONS:
        con.execute(f"CREATE OR REPLACE TEMP VIEW rets AS {_returns_sql(spine, sessions, cutoff)}")
        # Market-relative: the equal-weighted cross-sectional mean of the same
        # session. Decision 0021 — a pooled average of market-relative returns is
        # identically zero, so the demean is the comparison, not the estimator.
        con.execute("CREATE OR REPLACE TEMP VIEW mkt AS SELECT date, avg(ret) m FROM rets GROUP BY 1")
        # The size and round-trip filters already live in the mart's
        # eligible_for_research, applied once where they can be counted, rather
        # than re-implemented in every study that needs them.
        df = con.execute(EVENT_JOIN_SQL).df().dropna(subset=["ab"])

        cohorts = power.cohort_collapse(df["tdate"], df["ab"], freq="M")
        # THE LAG MUST COVER THE LABEL OVERLAP (decision 0033). A 12-month label
        # on monthly cohorts overlaps 11/12; the Newey-West rule alone picks ~5
        # and understates the correction, which is what briefly made this look
        # POWERED when it was not.
        label_periods = max(1, round(months))
        infl, _ = power.serial_inflation(cohorts, label_periods=label_periods)
        out.append(Row(
            horizon=label, sessions=sessions, months=months,
            n_events=len(df), n_cohorts=len(cohorts),
            cohort_sd=power.cohort_sd(cohorts), inflation=infl,
            mde=power.mde_serial_corrected(cohorts, label_periods=label_periods),
        ))
    return out


def main() -> int:
    print("POWER GRID — eligible, size-filtered, market-relative, adjusted spine")
    print("  bound scales with horizon (decision 0028); lag covers the label overlap (0033)")
    print(f"\n  {'horizon':>11} {'n':>7} {'coh':>4} {'sd':>9} {'infl':>6} "
          f"{'MDE':>9} {'bound':>8} {'verdict':>14}")
    rows = grid()
    for r in rows:
        print(r.render())
    print(f"\n  excluded, unresolved_identity: {unresolved():,} eligible row(s) with no security_id")
    powered = [r for r in rows if r.powered]
    print(f"\n  {len(powered)} of {len(rows)} horizons reach their bound"
          + (f": {', '.join(r.horizon for r in powered)}" if powered else ""))
    if powered:
        print("  Reported as MARGINAL. A study registered here sits near its own")
        print("  detection floor, which is the condition power.py exists to flag.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
